<template>
  <article>
    <h1>Contact page</h1>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
    <section>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, quia fugit magni perspiciatis et qui perferendis laboriosam odio ipsam commodi vel repellendus? Sint ab nihil, animi quae illum deleniti unde. Vitae nobis exercitationem cum necessitatibus ut unde molestias tenetur, magni amet doloremque, temporibus explicabo neque tempora a. Magni molestiae sint ducimus amet voluptas similique iste autem minus libero dolor. Cupiditate, perspiciatis ullam. Ut corrupti fugit architecto veritatis officia provident magnam, tenetur sint quidem quas deleniti et eius sunt officiis sed recusandae culpa velit placeat excepturi neque aperiam expedita. Itaque corporis assumenda nesciunt consectetur tempora eveniet numquam mollitia beatae enim hic ea commodi, temporibus dolore nisi exercitationem saepe doloribus necessitatibus, id illo sequi reprehenderit voluptates. Magni voluptatibus veritatis mollitia non excepturi esse repellendus. Ab cumque atque dolores eveniet! Voluptate ea quod numquam, ipsa perspiciatis deleniti perferendis id iusto excepturi voluptates vitae, exercitationem deserunt ipsam illo dolor aperiam reprehenderit officia repellendus. Odit fugiat, officia aspernatur, vel cupiditate nam corrupti alias autem doloribus facilis eos. Aliquid fugiat, soluta ea nobis quibusdam facere a aperiam rem eveniet, laborum explicabo saepe, est nisi aut inventore provident libero magnam voluptate illo voluptatum. Numquam voluptate, totam, modi esse sapiente quod inventore ex repudiandae et sit, qui minus.
      </p>
    </section>
  </article>
</template>

<script>
export default {
  name: "Contact"
}
</script>

<style>

</style>